insert into role(role) values ('Director');
insert into role(role) values ('Accountant');
insert into role(role) values ('Programmer');
insert into rule(rule) values ('Rule over all');
insert into rule(rule) values ('To count money');
insert into rule(rule) values ('Earn a salary');
insert into rule(rule) values ('Write a code');
insert into rule(rule) values ('Fix bugs');
insert into rule(rule) values ('Running around the office w/firebluster');
insert into role_rules(role_id, rule_id) values (1, 1);
insert into role_rules(role_id, rule_id) values (1, 6);
insert into role_rules(role_id, rule_id) values (2, 2);
insert into role_rules(role_id, rule_id) values (2, 3);
insert into role_rules(role_id, rule_id) values (3, 4);
insert into role_rules(role_id, rule_id) values (3, 5);
insert into role_rules(role_id, rule_id) values (3, 6);
insert into users(username, role_id) values ('Nick Smith', 1);
insert into users(username, role_id) values ('Tamara Chernych', 2);
insert into users(username, role_id) values ('Gleb Pavlovich', 2);
insert into users(username, role_id) values ('Mike Nike', 3);
insert into users(username, role_id) values ('Gregory Alan Isaakov', 3);
insert into state(state) values ('Done');
insert into state(state) values ('In progress');
insert into state(state) values ('Cancelled');
insert into state(state) values ('Confirmed');
insert into category(name) values ('request');
insert into category(name) values ('offer');
insert into category(name) values ('internal application');
insert into item(item_name, username_id, category_id, state_id) values ('Buy new car', 1, 2, 3);
insert into item(item_name, username_id, category_id, state_id) values ('Fix all bugs in tracker', 5, 3, 2);
insert into comments(comment, item_id) values ('fua', 1);
insert into comments(comment, item_id) values ('ok, it will be done', 2);
insert into attaches(file_name, item_id) values ('dickpic.jpg', 1);
